### ISSUE TITLE
Failed to add reference to 'Reactive.EventAggregator'

### ISSUE THREAD

**Issue by ibebbs** [shiftkey/Reactive.EventAggregator#14]
Hi,

I've used Reactive.EventAggregator v1.0.1 for some time but have just tried upgrading to V2.0.0. Unfortunately the package upgrade failed and whenever I attempt to manually uninstall and re-install the package I get the following error:

> Install failed. Rolling back...
> Install-Package : Failed to add reference to 'Reactive.EventAggregator'.
> At line:1 char:1
> - Install-Package Reactive.EventAggregator
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

This seems to only happen when trying to install the package into a Windows 8.1 portable app.

I have forked the project and tried changing nuspec target framework values to no avail.

Any ideas?

Thanks,
  Ian Bebbington

**Comment by shiftkey** [comment]
Whoops, totally forgot to come back to this. @ibebbs please let me know if you still care.
