### ISSUE TITLE
Update to Rx.NET 3.x or accept PR

### ISSUE THREAD

**Issue by BrainCrumbz** [shiftkey/Reactive.EventAggregator#15]
Hello

as you may know, recently Rx.NET has been updated to v3, with at least a major breaking change due to change of package IDs. 
This means that currently, including Reactive.EventAggregator implies to also reference old Rx.NET v2, next to the v3 package in same project.

Would you consider updating this package to depend on Rx.NET 3.x (whether directly working on it, or maybe discussing about a PR) ?

Thank you!

**Comment by shiftkey** [comment]
@BrainCrumbz I'd be happy to accept a PR and organize a new release of this!
