### ISSUE TITLE
Update NuGet package to include the new .NetStandard support

### ISSUE THREAD

**Issue by MetaFight** [shiftkey/Reactive.EventAggregator#25]
Hi,

First of all, thanks for this nice and simple event aggregator that *isn't tied to the UI layer*.

Here's the issue.  It looks like the pull request to add .NetStandard support has built successfully, and has generated an appropriate NuGet package, but that package hasn't been submitted to NuGet.org yet.

https://ci.appveyor.com/project/shiftkey/reactive-eventaggregator/build/1.1.77/artifacts

I would happy do this myself but I'm assuming only the package author can do this.

This is, I guess, just a gentle nudge to make it happen!

Thanks 😅

**Comment by shiftkey** [comment]
I _believe_ it's this version: https://www.nuget.org/packages/Reactive.EventAggregator/4.0.0-rc

`Install-Package Reactive.EventAggregator -Pre` should do the trick.

If you're happy with that version, I can push up a stable version!

**Comment by MetaFight** [comment]
Oh, cool.

I'll give it a test run tomorrow.

I'll let you know how it goes.

Cheers!

Sent from my electrophonic typewriter.

________________________________

**Comment by MetaFight** [comment]
OK, so I tested the prerelease package and it seems to work fine.

My scenario involves a WPF project using .NET 4.6.1 and a class library using .NET Standard 1.6.

**Comment by shiftkey** [comment]
Cool. I'll leave this open as a reminder to get a stable release out.

**Comment by kl1mm** [comment]
Hey shiftkey, any idea when the stable release will be available on nuget?
Thanks kl1mm
